from .order_management import (
    LAZADA_ORDER_INQUIRY_AUTO_RESPONSE_PROMPT,
    LAZADA_ORDER_INQUIRY_DRAFT_RESPONSE_PROMPT,
    LAZADA_ORDER_CANCELLATION_AUTO_RESPONSE_PROMPT,
    LAZADA_ORDER_CANCELLATION_DRAFT_RESPONSE_PROMPT,
)

from .product_consultation import (
    LAZADA_PRODUCT_CONSULTATION_AUTO_RESPONSE_PROMPT,
    LAZADA_PRODUCT_CONSULTATION_DRAFT_RESPONSE_PROMPT,
)

from .human_support import LAZADA_HUMAN_SUPPORT_PROMPT
from .default_topic import DefaultTopic
from .prompt_by_topic import get_prompt_template_by_topic

__all__ = [
    "LAZADA_ORDER_INQUIRY_AUTO_RESPONSE_PROMPT",
    "LAZADA_ORDER_INQUIRY_DRAFT_RESPONSE_PROMPT",
    "LAZADA_ORDER_CANCELLATION_AUTO_RESPONSE_PROMPT",
    "LAZADA_ORDER_CANCELLATION_DRAFT_RESPONSE_PROMPT",
    "LAZADA_PRODUCT_CONSULTATION_AUTO_RESPONSE_PROMPT",
    "LAZADA_PRODUCT_CONSULTATION_DRAFT_RESPONSE_PROMPT",
    "LAZADA_HUMAN_SUPPORT_PROMPT",
    "DefaultTopic",
    "get_prompt_template_by_topic",
]
