from .agent_router import CUSTOMER_COORDINATOR_TEMPLATE
from .tool_driven_specialist import SPECIALIST_AGENT_TEMPLATE
from .ticket_triage_analyzer import TICKET_TRIAGE_ANALYSIS_TEMPLATE
from .auto_response_complete import AUTO_RESPONSE_COMPLETE_TEMPLATE

__all__ = [
    "CUSTOMER_COORDINATOR_TEMPLATE",
    "SPECIALIST_AGENT_TEMPLATE",
    "TICKET_TRIAGE_ANALYSIS_TEMPLATE",
    "AUTO_RESPONSE_COMPLETE_TEMPLATE",
]
