from .lazada import (
    LAZADA_ORDER_INQUIRY_AUTO_RESPONSE_PROMPT,
    LAZADA_ORDER_INQUIRY_DRAFT_RESPONSE_PROMPT,
    LAZADA_ORDER_CANCELLATION_AUTO_RESPONSE_PROMPT,
    LAZADA_ORDER_CANCELLATION_DRAFT_RESPONSE_PROMPT,
    LAZADA_PRODUCT_CONSULTATION_AUTO_RESPONSE_PROMPT,
    LAZADA_PRODUCT_CONSULTATION_DRAFT_RESPONSE_PROMPT,
    LAZADA_HUMAN_SUPPORT_PROMPT,
)

__all__ = [
    "LAZADA_ORDER_INQUIRY_AUTO_RESPONSE_PROMPT",
    "LAZADA_ORDER_INQUIRY_DRAFT_RESPONSE_PROMPT",
    "LAZADA_ORDER_CANCELLATION_AUTO_RESPONSE_PROMPT",
    "LAZADA_ORDER_CANCELLATION_DRAFT_RESPONSE_PROMPT",
    "LAZADA_PRODUCT_CONSULTATION_AUTO_RESPONSE_PROMPT",
    "LAZADA_PRODUCT_CONSULTATION_DRAFT_RESPONSE_PROMPT",
    "LAZADA_HUMAN_SUPPORT_PROMPT",
]
