from .base import (
    CUSTOMER_COORDINATOR_TEMPLATE,
    SPECIALIST_AGENT_TEMPLATE,
    TICKET_TRIAGE_ANALYSIS_TEMPLATE,
    AUTO_RESPONSE_COMPLETE_TEMPLATE,
)

from .workflow import (
    INIT_AGENT_PROMPT_TEMPLATE,
    TOPIC_AGENT_PROMPT_TEMPLATE,
    POST_PROCESSING_PROMPT_TEMPLATE,
)

from .domain.lazada import (
    LAZADA_ORDER_INQUIRY_AUTO_RESPONSE_PROMPT,
    LAZADA_ORDER_INQUIRY_DRAFT_RESPONSE_PROMPT,
    LAZADA_ORDER_CANCELLATION_AUTO_RESPONSE_PROMPT,
    LAZADA_ORDER_CANCELLATION_DRAFT_RESPONSE_PROMPT,
    LAZADA_PRODUCT_CONSULTATION_AUTO_RESPONSE_PROMPT,
    LAZADA_PRODUCT_CONSULTATION_DRAFT_RESPONSE_PROMPT,
    LAZADA_HUMAN_SUPPORT_PROMPT,
    DefaultTopic,
    get_prompt_template_by_topic,
)

__all__ = [
    # Base templates
    "CUSTOMER_COORDINATOR_TEMPLATE",
    "SPECIALIST_AGENT_TEMPLATE",
    "TICKET_TRIAGE_ANALYSIS_TEMPLATE",
    "AUTO_RESPONSE_COMPLETE_TEMPLATE",

    # Workflow templates
    "INIT_AGENT_PROMPT_TEMPLATE",
    "TOPIC_AGENT_PROMPT_TEMPLATE",
    "POST_PROCESSING_PROMPT_TEMPLATE",

    # Domain-specific templates
    "LAZADA_ORDER_INQUIRY_AUTO_RESPONSE_PROMPT",
    "LAZADA_ORDER_INQUIRY_DRAFT_RESPONSE_PROMPT",
    "LAZADA_ORDER_CANCELLATION_AUTO_RESPONSE_PROMPT",
    "LAZADA_ORDER_CANCELLATION_DRAFT_RESPONSE_PROMPT",
    "LAZADA_PRODUCT_CONSULTATION_AUTO_RESPONSE_PROMPT",
    "LAZADA_PRODUCT_CONSULTATION_DRAFT_RESPONSE_PROMPT",
    "LAZADA_HUMAN_SUPPORT_PROMPT",

    # Lazada utilities
    "DefaultTopic",
    "get_prompt_template_by_topic",
]
